spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CitySights
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate.ddl-auto: update
    show-sql: true
